name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev
    - name: Build MkDocs Site
      run: |
        poetry run mkdocs build --verbose --clean
    - name: Add CNAME for Custom Domain
      run: |
        echo "www.pycatcher.com" > site/CNAME
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site